# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  thebrutesquad.net:
    site_hosts:
      - thebrutesquad.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:roots/masoninthesis/thebrutesquad-net.git
    site_install: true
    site_title: The Brute Squad | Net
    admin_user: admin
    admin_password: admin
    admin_email: admin@thebrutesquadnet.dev
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://thebrutesquadnet.dev
      wp_siteurl: http://thebrutesquadnet.dev/wp
      wp_env: development
      db_name: thebrutesquadnet_dev
      db_user: thebrutesquadnet_dbuser
      db_password: thebrutesquadnet_dbpassword
